version: '3'
services:
  api:
    build: docker/api
    volumes:
      - ./api:/api
    working_dir: /api
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    networks:
      - db
      - external

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    networks:
      - db
      - external

volumes:
  db: {}

networks:
  db:
    internal: true
  external:
    internal: false
